
public class MAIN {

	/**
	 * MAIN FOR GORT
	 */
	public static void main(String[] args) {
	

		//GET INSTRUCTIONS
			//FROM FILE
			//FROM WEB
			//START/STOP COMMANDS
			//CREATE INSTRUCTIONS
			//ALLERGY/PREFERENCE CHECK&SUBSTITUTION
		//ASSEMBLE INGREDIENTS
			//INVENTORY CHECK - MATERIALS AND TOOLS, SERVEWARE
			//QUALITY CHECK
			//QUANTITY CHECK
			//UNIDENTIFIED MATERIAL HANDLING
		//PERFORM INSTRUCTIONS ON INGREDIENTS
			//SPECIFIC INGREDIENT ACTIONS
			//NON-SPECIFIC ACTIONS
				//TOOL USE
				//MACHINE USE
				//USED TOOL/MACHINE DESIGNATION; MESS/CLEAN DETECTION
			//TIMING
			//MULTISTEP ACTIONS
				//INTERMEDIATE INGREDIENTS
				//QUALITY CHECK MID-PROCESS
		//SERVE
			//TRANSFER ACTIONS
			//STYLE POINTS
		//CLEAN-UP
			//MESS/CLEAN DETECTION
			//MESS REMOVAL
			//INVENTORY CHECK
			//LEFTOVERS
		
		//PERFORM INVENTORY
			//INVENTORY QUALITY CHECK
		

					
		//ROBOTIC CONTROLS
			//MOVEMENT
			//SENSING (SEE SENSOR INVENTORY BELOW)
			//ENVIRONMENTAL AWARENESS
			//SAFETY
			//GRIP
			//SWITCHING UTENSILS
			//ROTARY MOVEMENT
		
					
		//SENSOR INVENTORY
				//ARM SENSOR BUNDLE (AB)
					//INFRARED THERMOMETER
					//RFID TAG READER
					//UV CAMERA?
					//WORKSPACE CAMERA
				//ARM (A)
					//TORQUE
					//GRIP PRESSURE
				//BODY (B)
					//PLUMB SENSING
					//ULTRASONIC
					//UV LIGHT
					//CAMERA TURRET?
				//EXTERNAL TO ROBOT (E)
					//CAMERAS
						//+/-X
						//+/-Z
						//-Y
				//CLOCK IN SOFTWARE
						
					
					
					
			
	}

}
