// readfile

// READFILE IS SEPARATE FROM type/item BECAUSE IT WRITES/READS TO FILES 
// AND I DON'T WANT TO HAVE TO DEAL WITH try/catch ELSEWHERE

/*
 * BOOT:
 * READS PANTRY TO ARRAYLIST & SORTS BY nD
 * CONVERTS INVENTORY TO ARRAYLIST & SORTS BY nD
 * CHECKS storageLifeParam AND DISCARDS OLD FOODS 
 */

// JEEVES
 
/* 
 * readJeeves
 * COMAPRES LIST OF COMMON FOODS' QUANTITIES TO CURRENT INVENTORY
 * WRITES LIST OF NEEDED FOODS
 * TODO HARDCODE LIST OF NEEDED FOODS?
 * 
 * callJeeves
 * CHECKS INVENTORY OF SPECIFIC OBJECT
 * ALSO USED WHEN GENERATING RECIPIES
 */
